### PR TITLE
refactoring config Node edit Forms with i18N en, de

### PR DESCRIPTION
**Pull request by svenflender**
Hi,

i have refactored the config Node Edit Form and added i18n Files for en/de
The help File has still to be translated and refactored.

best Regards
Sven

### CODE REVIEW

**Comment by svenflender** [comment]
Hi,

i have refactored the config Node Edit Form and added i18n Files for en/de
The help File has still to be translated and refactored.

I also changed the Icons from png to svg

best Regards
Sven

**Comment by Supergiovane** [comment]
Hi Sven
i've pushed the new node. 
Because i touched other code, i need you, please to cancel this pull request, pull the new code and then push again a new pull request.
Sorry for that. Thank you!

**Comment by svenflender** [comment]
why you couldn't merge the pull request?

**Comment by Supergiovane** [comment]
Sorry Sven. With this coronavirus i’m so busy, that i’ve made some confusion. 
I saw your new pull request. I’ll take a look tomorrow. Now i need to go out in the grocery for the whole family. Italy is closed down and i can exit only for grocey.

**Pull request closed without merging**
