### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by SystemKeeper**
Hello @Supergiovane ,

as discussed earlier, here's a suggestion for a first code-cleanup. Feel free to use it as you like or parts of it.
I wasn't sure about some checks, so I left them in (for example I'm still not sure why you surrounded `oGA `with a try-catch block). It's working fine on my end, but I must admit that my flows do not cover all cases.
Let me know what you think.

### CODE REVIEW

**Comment by Supergiovane** [comment]
Thank you. Monday i’ll give a look! Thank you. I tend to ever use try catch whenever i have less time to think for a possible issues.

**Comment by Supergiovane** [comment]
Thank you. I'll try in my office for some days and then i'll commit the changes toghether with a new version.

**Comment by SystemKeeper** [comment]
> Hmm... it broked the RBE OUTPUT filter. Must check...

I was just about to post this... I noticed this while looking through the code. Problem is at https://github.com/Supergiovane/node-red-contrib-knx-ultimate/blob/f24b8d1a06c7ba694023d3b95ec1277356101215/knxUltimate-config.js#L453
This never happens as we check for undefined before: 
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/blob/f24b8d1a06c7ba694023d3b95ec1277356101215/knxUltimate-config.js#L432

I'll take a look later and commit a fix, sorry.

**Comment by Supergiovane** [comment]
;)

**Pull request merged**
