### PR TITLE
Code cleanup #2

### PR DESCRIPTION
**Pull request by SystemKeeper**
Hello,

any reason why you reverted the complete pull-request? Would've been easier to just commit a fix ;-)
This PR includes the cleanup as before and should fix RBE filter.
Let me know what you think.

### CODE REVIEW

**Comment by Supergiovane** [comment]
Hello, yes, because if, in the meantime, someone download the code from github, this doesn't work.
Sorry for that ;-)
I'll take a look!
Thank you again!

**Comment by Supergiovane** [comment]
Yes Sorry, i could have done that. The hurry.... so bad.

**Comment by Supergiovane** [comment]
The RBE input filter is again broken. I'll dive into the code to fix it.

**Comment by SystemKeeper** [comment]
@Supergiovane : There is in `checkRBEInputFromKNXBusAllowSend` ?!

**Comment by Supergiovane** [comment]
Yes, but this in bold avoids updating the currentPayload:

```
if **(typeof _node.currentPayload === "undefined")** {
                _node.currentPayload = _KNXTelegramPayload;
                return true;
            } 
```

Maybe you wanna write this instead?
```
if **(typeof _KNXTelegramPayload === "undefined")**
         _node.currentPayload = _KNXTelegramPayload;
                return true;
            } 
```

**Comment by Supergiovane** [comment]
Yes, but for some reasons, it doesn't work.

**Comment by Supergiovane** [comment]
You've done a great job in shrinking up the code. Do you work currently as js developer?

**Comment by SystemKeeper** [comment]
Interesting - does it work now with your changes? Maybe we could leave this in development for a few days, I'd like to take a look why my solution isn't working, if thats ok with you.
Thanks, glad you like I'm not working with js on a regular basis, but sometimes its part of my job.

**Comment by Supergiovane** [comment]
Hello
yes it does work.
I'll leave it in the developer branch until i'll add other features, so you have plenty of time.
You code should word, but it doesn't.
If you send multiple time the same value to the node, the RBE filter doesn't kick in, nor the debug window shows any exception raised by the code.

**Comment by Supergiovane** [comment]
Hello,
found another issue.
The node set to "listen to all group address" does not outputs the device name linked to the group address in the node's status and maybe in the flow.
I've merged your PR and i'll do some modifications that i'm working on.
This is for your info.
Cheers and again thank you!

**Pull request merged**
