### PR TITLE
Design Feature

### PR DESCRIPTION
**Pull request by svenflender**
Hi,

i have designed a Logo and a new Icon for the knxUltimate Node.
I also added some changes to the Node color and category.
What do you think?

Best Regards
Sven

### CODE REVIEW

**Comment by svenflender** [comment]
thank you. No, only as Hobby.
I will have a look at the two nodes this evening.

I have many additional Ideas, how can i reach you in the best way to discuss them?

Best Regards
Sven

**Comment by Supergiovane** [comment]
> thank you. No, only as Hobby.
> I will have a look at the two nodes this evening.
> 
> I have many additional Ideas, how can i reach you in the best way to discuss them?
> 
> Best Regards
> Sven

We can stay here on gitHub, so i have all under control.

**Comment by svenflender** [comment]
What do you think?

image

**Comment by Supergiovane** [comment]
Hi Sven
Very good but instead of pink for the Watchdog, i’ll go for a light green (more light green as the device node). 
The idea is to make all “service” nodes, with the same color as the device node, but heller. 
Icons are great.

**Comment by Supergiovane** [comment]
Tomorrow i’ll merge your pull request. 👍🏻

**Comment by svenflender** [comment]
> Hi Sven
> Very good but instead of pink for the Watchdog, i’ll go for a light green (more light green as the device node).
> The idea is to make all “service” nodes, with the same color as the device node, but heller.
> Icons are great.

image

**Comment by svenflender** [comment]
> Tomorrow i’ll merge your pull request. 👍🏻

please wait. I want to refactor also the Icons in the Config Panel. I am still searching a Method to load the Icons local instead from github

image

**Comment by svenflender** [comment]
After Icon Refactoring i wanted to integrate i18n so you could have the Menues translated in different languages. I will start with english and german... ;)

**Comment by Supergiovane** [comment]
Ok, the icons, yes, they adhere to KNX standard, but are awful. I admit that. 
About i18n, it’s a good idea. 
I would have first the pullmreqiest merged, because i need to add some things for an user that asked me on knx-user-forum. 
As soon as you ended the development of this pull request, please create another different pull request for the i18n. 
Colors are now ok!
Thanks.

**Pull request merged**
