### PR TITLE
Add standard

### PR DESCRIPTION
**Pull request by croghostrider**
Hi Supergiovane,

I found some duplicate keys in object literals and inconsistent code style
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/blob/c10fa7a5e0f1591ff5f05b76c569609b35ec2115/KNXEngine/dptlib/dpt2.js#L114-L115
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/blob/c10fa7a5e0f1591ff5f05b76c569609b35ec2115/KNXEngine/dptlib/dpt2.js#L53-L54
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/blob/c10fa7a5e0f1591ff5f05b76c569609b35ec2115/KNXEngine/dptlib/dpt2.js#L121-L122
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/blob/c10fa7a5e0f1591ff5f05b76c569609b35ec2115/KNXEngine/dptlib/dpt2.js#L127-L128

I think it is a good idea to add a linter to this project, I would recommend [standard js](https://standardjs.com/).
After this pull request, the code contains 767 issues that require a manual intervention.

Here all issues:

> 152    Do not access Object.prototype method 'hasOwnProperty' from target object. (no-prototype-builtins)
87     Expected '===' and instead saw '=='. (eqeqeq)
83     Identifier 'apdu_data' is not in camel case. (camelcase)
74     Identifier 'KNXConstants_1' is not in camel case. (camelcase)
39     Expected 'undefined' and instead saw 'void'. (no-void)
32     't' is assigned a value but never used. (no-unused-vars)
30     Expected '!==' and instead saw '!='. (eqeqeq)
19     Unexpected comma in middle of array. (no-sparse-arrays)
18     Identifier 'max_mantissa' is not in camel case. (camelcase)
15     'e' is not defined. (no-undef)
14     Identifier 'KNXPacket_1' is not in camel case. (camelcase)
12     'ret' is not defined. (no-undef)
12     Unexpected var, use let or const instead. (no-var) (warning)
12     Identifier 'KNXUtils_1' is not in camel case. (camelcase)
9      Empty block statement. (no-empty)
9      Unexpected tab character. (no-tabs)
9      Unnecessary escape character
7      Identifier 'opt_random' is not in camel case. (camelcase)
7      eval can be harmful. (no-eval)
6      'util' is assigned a value but never used. (no-unused-vars)
6      'max_mantissa' is not defined. (no-undef)
6      'goTimerGo' is not defined. (no-undef)
5      'match' is not defined. (no-undef)
5      Expected an error object to be thrown. (no-throw-literal)
5      Identifier 'cloned_dpt' is not in camel case. (camelcase)
5      Identifier 'header_length' is not in camel case. (camelcase)
4      'apdu_data' is defined but never used. (no-unused-vars)
4      Unexpected mix of '&&' and '||'. Use parentheses to clarify the intended order of operations. (no-mixed-operators)
4      'result' is not defined. (no-undef)
4      Identifier 'KNXAddress_1' is not in camel case. (camelcase)
4      Identifier 'DeviceInfo_1' is not in camel case. (camelcase)
4      Identifier 'ServiceFamilies_1' is not in camel case. (camelcase)
3      Block is redundant. (no-lone-blocks)
2      Identifier 'opt_rnd' is not in camel case. (camelcase)
2      Expected a 'break' statement before 'case'. (no-fallthrough)
2      'timeoutError' is assigned a value but never used. (no-unused-vars)
2      Identifier 'TunnelCRI_1' is not in camel case. (camelcase)
2      Getter is not present for class setter 'gateway'. (accessor-pairs)
2      Identifier 'KNXHeader_1' is not in camel case. (camelcase)
2      Unexpected lexical declaration in case block. (no-case-declarations)
2      The array literal notation [] is preferable. (no-array-constructor)
2      'KnxConstants' is assigned a value but never used. (no-unused-vars)
2      'ret' is assigned a value but never used. (no-unused-vars)
1      Parsing error
1      '_0' is assigned a value but never used. (no-unused-vars)
1      Identifier 'crypto_verify_32' is not in camel case. (camelcase)
1      Identifier 'crypto_scalarmult' is not in camel case. (camelcase)
1      Identifier 'crypto_scalarmult_base' is not in camel case. (camelcase)
1      Identifier 'crypto_hashblocks_hl' is not in camel case. (camelcase)
1      Identifier 'crypto_hash' is not in camel case. (camelcase)
1      Identifier 'crypto_sign_direct' is not in camel case. (camelcase)
1      Identifier 'crypto_sign_direct_rnd' is not in camel case. (camelcase)
1      Identifier 'curve25519_sign' is not in camel case. (camelcase)
1      Identifier 'crypto_sign_open' is not in camel case. (camelcase)
1      Identifier 'curve25519_sign_open' is not in camel case. (camelcase)
1      'signMessage' is defined but never used. (no-unused-vars)
1      'openMessage' is defined but never used. (no-unused-vars)
1      'sign' is defined but never used. (no-unused-vars)
1      'verify' is defined but never used. (no-unused-vars)
1      Expected a 'break' statement before 'default'. (no-fallthrough)
1      Expected a conditional expression and instead saw an assignment. (no-cond-assign)
1      Use path.join() or path.resolve() instead of string concatenation. (n/no-path-concat)
1      'element' is assigned a value but never used. (no-unused-vars)
1      'FrameType' is assigned a value but never used. (no-unused-vars)
1      'OnOff' is assigned a value but never used. (no-unused-vars)
1      'Priority' is assigned a value but never used. (no-unused-vars)
1      Getter is not present for class setter 'data'. (accessor-pairs)
1      'ConnectionType' is assigned a value but never used. (no-unused-vars)
1      'ConnectionTypes' is assigned a value but never used. (no-unused-vars)
1      'Medium' is assigned a value but never used. (no-unused-vars)
1      'KnxProtocol' is assigned a value but never used. (no-unused-vars)
1      'ConnectionStatus' is assigned a value but never used. (no-unused-vars)
1      'sysLogger' is assigned a value but never used. (no-unused-vars)
1      Unnecessary try/catch wrapper. (no-useless-catch)
1      'TunnelTypes' is assigned a value but never used. (no-unused-vars)
1      'Server' is assigned a value but never used. (no-unused-vars)
1      'readHistory' is assigned a value but never used. (no-unused-vars)
1      'delay' is assigned a value but never used. (no-unused-vars)
1      Array.prototype.filter() expects a value to be returned at the end of arrow function. (array-callback-return)
1      Unexpected control character(s) in regular expression
1      'fs' is assigned a value but never used. (no-unused-vars)
1      'mkdirp' is assigned a value but never used. (no-unused-vars)
1      Expected the Promise rejection reason to be an Error. (prefer-promise-reject-errors)
1      'newVal' is already defined. (no-redeclare)
1      'correctJson' is already defined. (no-redeclare)

### CODE REVIEW

**Comment by Supergiovane** [comment]
Hi
Thank you. 
About code literals, it's a matter of typo.

This code
```
// 2.011 state control 
 "001" : { "use" : "FB", 
```

Should be

// 2.**011** state control 
 "**011**" : { "use" : "FB", 

and should have the right description. Maybe a copy/paste/forgot!
Tomorrow i'll take a look at all.

**Comment by croghostrider** [comment]
I know it's a typo, but a linter would help find the typos.
The duplicate keys are fixed in my pull request.

**Comment by Supergiovane** [comment]
Hi,
Have you added your[ custom DPT](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/issues/200) as well?

**Comment by croghostrider** [comment]
no, I will do that in another pull request. I'm not ready yet.

**Comment by Supergiovane** [comment]
KNX-Ultimate outputs also a RAW value, you could use that to decode/encode your telegram.
Search SEND RAW VALUE TO THE BUS  [in this page](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/2.-Node-Configuration)

**Pull request merged**
