### PR TITLE
new Node-RED compliant KNX Icon

### PR DESCRIPTION
**Pull request by svenflender**
Hi,
I have created a new KNX Logo for the ultimate node to be more compliant to the Node-RED specification.

Best Regards
Sven

### CODE REVIEW

**Comment by Supergiovane** [comment]
Hey Sven, thank you. I'll check the file ASAP!

**Comment by Supergiovane** [comment]
Hello
Are you able to move the logo 1 or 2 pixel to the right, or maybe make it a little bit smaller?
The square input pin interfere with the logo.
Thank you.
Node-RED

**Comment by svenflender** [comment]
Hi,
i have changed the size. Hope it fits now.
Let me know if you need something else.

**Comment by Supergiovane** [comment]
Thank you Sven for your contribution to knx-ultimate!
:-)

**Comment by Supergiovane** [comment]
> But if you remove the align: "left" in the html code the Logo from the first Version should Fit.
> Align: left or right is only intended if you have a node without input on the left or right side.
> Can you please try this first?
> 
Hello Sven
left: puts the icon near the input pin
right: puts the icon near the right pin.
;-)

**Pull request merged**
