### PR TITLE
Refactoring + i18n for config Node

### PR DESCRIPTION
**Pull request by svenflender**

### CODE REVIEW

**Comment by svenflender** [comment]
added refactoring and translation for Scene Controller Help file

**Comment by Supergiovane** [comment]
Hi Sven,
great job in translating. I started Italian translation as well.
As soon as you can, can you post a sample on how translating an entire page, for example README.MD or the contextual help of the node html file?
Thanks.

**Comment by Supergiovane** [comment]
Hei Sven, great job in translating.
Do you know how to translate README.MD as well?

**Comment by svenflender** [comment]
Hi,
Thank you!
you can't translate the README.MD cause this is a File used for GitHub and not in Node-Red.

You can translate in Node-RED:
- Node Edit Forms
- JS Variables
- Node Help Text

See: https://nodered.org/docs/creating-nodes/i18n

Next week i will try to translate the missing parts...it's more work than i thought, cause i refactor also the HTML Code.

Best Regards
Sven

**Comment by Supergiovane** [comment]
Hi Sven, 
yes i've saw the work. Very time consuming.
Too bad GitHub hasn't a sort of i18n self implemented (for example README.DE.MD, README.EN.MD, README.IT.MD) and so on.

**Pull request merged**
